language: node_js
node_js:
  - 14
branches:
  only:
    - main
cache:
  directories:
    - node_modules
addons:
  ssh_known_hosts:
    - $IP
before_install:
  - openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - npm install
scripts:
  - npm cache clean --force
  - npm run lint
  - npm run build
  - docker build -t registry.cn-chengdu.aliyuncs.com/octoveau/large-screen:4.0 .
  - echo $pwd | docker login --username=looper卓敏 registry.cn-chengdu.aliyuncs.com --password-stdin
  - docker push registry.cn-chengdu.aliyuncs.com/octoveau/large-screen:4.0
  # - ssh root@$IP -o StrictHostKeyChecking=no
after_success:
  # - rsync -az --delete ./dist/* root@$IP:/www/looper/large-screen/
  # - rsync -az --delete ./bin/* root@$IP:/www/looper/large-screen/
  # - rsync -az --delete ./Dockerfile root@$IP:/www/looper/large-screen/
  # - ssh  root@$IP "cd /www/looper/large-screen/;mkdir test1;exit"
